[package]
name = "verify_compile"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["runtime-tokio", "mysql"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"]}
